[package]
name = "paladin-memo-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = "1.44.1"
solana-sdk = "2.2.0"
solana-client = "2.2.0"
solana-rpc-client-api = "2.2.0"
anyhow = "1.0.97"
futures = "0.3.31"
futures-util = "0.3.31"
reqwest = "0.12.15"
